version: "3.8"
services:
  delivery_metrics:
    build: .
    container_name: delivery_metrics
    networks:
      - dm_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    ports:
      - "9090:9090"
    networks:
      - dm_net
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - dm_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  dm_net:
    driver: bridge
